//! Kernel contracts: the declared assumptions and comparison semantics that
//! evidence is produced under.

use serde::{Deserialize, Serialize};

/// How outputs of two realizations are compared.
///
/// The comparison mode is part of the contract: a tolerance is a declared
/// assumption recorded in the evidence, never an implementation detail.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Compare {
    /// Bit-exact equality. The only mode for integer kernels.
    Exact,
    /// Maximum permitted ULP distance between f32 results. NaN on either side
    /// is always a failure.
    MaxUlpF32(u32),
    /// Pass when `|expected - actual| <= abs + rel * |expected|`.
    ///
    /// The honest tolerance shape when a backend may contract or reorder
    /// float operations (e.g. fma): under cancellation no useful ULP bound
    /// exists, but an absolute bound derived from the declared input ranges
    /// does. The bound is part of the contract and must be justified by the
    /// `assumes(...)` clauses.
    AbsRelF32 { abs: f32, rel: f32 },
}

impl Compare {
    pub fn describe(&self) -> String {
        match self {
            Compare::Exact => "exact".to_string(),
            Compare::MaxUlpF32(n) => format!("f32 max_ulp={n}"),
            Compare::AbsRelF32 { abs, rel } => {
                format!("f32 |e-a| <= {abs:e} + {rel:e}*|e|")
            }
        }
    }
}

/// An `assumes(...)` clause the macro recognized as a specific structured
/// shape, in addition to keeping it in `Contract::assumes` as a
/// pretty-printed string. This is the data the SMT bounds prover
/// (`vericl-ir`) binds buffer `Length` variables from — it has no other way
/// to relate a `.len()` constraint to a specific declared assumption.
/// Buffer identity is by parameter name; the harness maps names to the IR's
/// `input(i)`/`output(j)` positions via the macro-generated `BUFFER_PARAMS`.
///
/// Recognizing more clause shapes only ever adds provable obligations —
/// never silently loosens one — so growing this enum is always sound.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum StructuredAssume {
    /// `A.len() == B.len()`.
    LenEq { a: &'static str, b: &'static str },
    /// `A.len() == <int literal>`.
    LenEqConst { a: &'static str, value: u64 },
}

/// Static contract metadata generated by `#[vericl::kernel]`.
#[derive(Debug, Clone, Copy)]
pub struct Contract {
    /// Kernel function name.
    pub kernel: &'static str,
    /// Hash of the kernel source tokens + contract + vericl version.
    ///
    /// v0 identity is source-level; an IR-level hash is a recorded upgrade
    /// path (see README "Locked decisions").
    pub source_hash: &'static str,
    /// Pretty-printed `assumes(...)` clauses.
    pub assumes: &'static [&'static str],
    /// The subset of `assumes(...)` the macro could parse into a structured
    /// shape (see [`StructuredAssume`]). Unrecognized clauses are simply
    /// absent here — they still appear in `assumes` above.
    pub structured_assumes: &'static [StructuredAssume],
    /// Declared comparison semantics.
    pub compare: Compare,
    /// Whether the `wrapping` clause is declared: the reference twin's
    /// integer `+`, `-`, `*`, `<<`, `>>` (and their compound-assign forms)
    /// use wrapping arithmetic instead of Rust's default checked/panicking
    /// behavior, matching WGSL's wrap-on-overflow semantics. A declared
    /// contract clause, not a silent approximation — see README "A first
    /// finding" for the analogous fma story.
    pub wrapping: bool,
}

/// Serializable form of a [`Contract`] for the evidence manifest.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct ContractRecord {
    pub assumes: Vec<String>,
    pub compare: String,
    pub wrapping: bool,
}

/// Identity a piece of evidence is bound to. Any mismatch between a stored
/// identity and the currently built kernel makes the evidence stale.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct Identity {
    pub source_hash: String,
    pub vericl_version: String,
    /// Content hash of the expanded CubeCL IR (see `vericl-ir::kernel_ir_hash`).
    ///
    /// `None` only for evidence produced without IR access — this crate is
    /// deliberately cubecl-free (see README "Locked decisions": "isolate
    /// all IR-facing code in one crate"), so `Contract::identity()` can
    /// never compute this itself; the harness sets it after computing it
    /// via `vericl-ir`. With both hashes populated, `verify()`'s whole-
    /// `Identity` comparison catches IR-level drift (e.g. a CubeCL upgrade
    /// that changes codegen without changing kernel source) in addition to
    /// source-level drift.
    #[serde(default)]
    pub ir_hash: Option<String>,
}

impl Contract {
    /// Source-level identity only — `ir_hash` is left `None` here since this
    /// crate cannot depend on cubecl to compute it (see [`Identity::ir_hash`]);
    /// callers with IR access fill it in afterward.
    pub fn identity(&self) -> Identity {
        Identity {
            source_hash: self.source_hash.to_string(),
            vericl_version: crate::VERSION.to_string(),
            ir_hash: None,
        }
    }

    pub fn record(&self) -> ContractRecord {
        ContractRecord {
            assumes: self.assumes.iter().map(|s| s.to_string()).collect(),
            compare: self.compare.describe(),
            wrapping: self.wrapping,
        }
    }
}
