//! Kernel contracts: the declared assumptions and comparison semantics that
//! evidence is produced under.

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

/// How outputs of two realizations are compared.
///
/// The comparison mode is part of the contract: a tolerance is a declared
/// assumption recorded in the evidence, never an implementation detail.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Compare {
    /// Bit-exact equality. The only mode for integer kernels.
    Exact,
    /// Maximum permitted ULP distance between f32 results. NaN on either side
    /// is always a failure.
    MaxUlpF32(u32),
    /// Pass when `|expected - actual| <= abs + rel * |expected|`.
    ///
    /// The honest tolerance shape when a backend may contract or reorder
    /// float operations (e.g. fma): under cancellation no useful ULP bound
    /// exists, but an absolute bound derived from the declared input ranges
    /// does. The bound is part of the contract and must be justified by the
    /// `assumes(...)` clauses.
    AbsRelF32 { abs: f32, rel: f32 },
}

impl Compare {
    pub fn describe(&self) -> String {
        match self {
            Compare::Exact => "exact".to_string(),
            Compare::MaxUlpF32(n) => format!("f32 max_ulp={n}"),
            Compare::AbsRelF32 { abs, rel } => {
                format!("f32 |e-a| <= {abs:e} + {rel:e}*|e|")
            }
        }
    }
}

/// An `assumes(...)` clause the macro recognized as a specific structured
/// shape, in addition to keeping it in `Contract::assumes` as a
/// pretty-printed string. This is the data the SMT bounds prover
/// (`vericl-ir`) binds buffer `Length` variables from — it has no other way
/// to relate a `.len()` constraint to a specific declared assumption.
/// Buffer identity is by parameter name; the harness maps names to the IR's
/// `input(i)`/`output(j)` positions via the macro-generated `BUFFER_PARAMS`.
///
/// Recognizing more clause shapes only ever adds provable obligations —
/// never silently loosens one — so growing this enum is always sound.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum StructuredAssume {
    /// `A.len() == B.len()`.
    LenEq { a: &'static str, b: &'static str },
    /// `A.len() == <int literal>`.
    LenEqConst { a: &'static str, value: u64 },
}

/// Static contract metadata generated by `#[vericl::kernel]`.
#[derive(Debug, Clone, Copy)]
pub struct Contract {
    /// Kernel function name.
    pub kernel: &'static str,
    /// Hash of the kernel source tokens + contract + vericl version.
    ///
    /// v0 identity is source-level; an IR-level hash is a recorded upgrade
    /// path (see README "Locked decisions").
    pub source_hash: &'static str,
    /// Pretty-printed `assumes(...)` clauses.
    pub assumes: &'static [&'static str],
    /// The subset of `assumes(...)` the macro could parse into a structured
    /// shape (see [`StructuredAssume`]). Unrecognized clauses are simply
    /// absent here — they still appear in `assumes` above.
    pub structured_assumes: &'static [StructuredAssume],
    /// Declared comparison semantics.
    pub compare: Compare,
    /// Whether the `wrapping` clause is declared: the reference twin's
    /// integer `+`, `-`, `*`, `<<`, `>>` (and their compound-assign forms)
    /// use wrapping arithmetic instead of Rust's default checked/panicking
    /// behavior, matching WGSL's wrap-on-overflow semantics. A declared
    /// contract clause, not a silent approximation — see README "A first
    /// finding" for the analogous fma story.
    pub wrapping: bool,
    /// Pretty-printed `instantiate(...)` entries (`"F = f32"`, `"taps =
    /// 3"`), one per generic type parameter or `#[comptime]` parameter the
    /// kernel declares. Empty for a non-generic, non-comptime kernel. The
    /// instantiation *values* are already part of `SOURCE_HASH` (they're in
    /// the raw contract attribute tokens the hash covers) — this field
    /// exists purely so evidence records what a kernel was monomorphized
    /// at, the same way `wrapping` records a declared clause.
    pub instantiate: &'static [&'static str],
    /// Names of the `#[vericl::helper]`-annotated functions this kernel
    /// declares via `uses(...)` (kernel composition). `[]` for a kernel that
    /// calls no helpers. Purely for evidence legibility — `identity()`
    /// (not `identity`/this struct) is what actually folds each used
    /// helper's identity into the recorded source hash; see its doc.
    pub uses: &'static [&'static str],
}

/// Serializable form of a [`Contract`] for the evidence manifest.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct ContractRecord {
    pub assumes: Vec<String>,
    pub compare: String,
    pub wrapping: bool,
    /// See [`Contract::instantiate`]. `[]` for a non-generic, non-comptime
    /// kernel. `#[serde(default)]` so evidence written before this field
    /// existed still loads (as `[]`) instead of hard-failing deserialization
    /// — unlike a source/IR hash change, adding this field never changes
    /// `SOURCE_HASH` for a kernel that doesn't use `instantiate(...)`, so an
    /// old manifest for such a kernel is otherwise still perfectly valid.
    #[serde(default)]
    pub instantiate: Vec<String>,
    /// See [`Contract::uses`]. `#[serde(default)]` for the same reason as
    /// `instantiate` above — old evidence for a non-composing kernel is
    /// unaffected by this field's addition.
    #[serde(default)]
    pub uses: Vec<String>,
}

/// Identity a piece of evidence is bound to. Any mismatch between a stored
/// identity and the currently built kernel makes the evidence stale.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct Identity {
    pub source_hash: String,
    pub vericl_version: String,
    /// Content hash of the expanded CubeCL IR (see `vericl-ir::kernel_ir_hash`).
    ///
    /// `None` only for evidence produced without IR access — this crate is
    /// deliberately cubecl-free (see README "Locked decisions": "isolate
    /// all IR-facing code in one crate"), so `Contract::identity()` can
    /// never compute this itself; the harness sets it after computing it
    /// via `vericl-ir`. With both hashes populated, `verify()`'s whole-
    /// `Identity` comparison catches IR-level drift (e.g. a CubeCL upgrade
    /// that changes codegen without changing kernel source) in addition to
    /// source-level drift.
    #[serde(default)]
    pub ir_hash: Option<String>,
}

impl Contract {
    /// Source-level identity only — `ir_hash` is left `None` here since this
    /// crate cannot depend on cubecl to compute it (see [`Identity::ir_hash`]);
    /// callers with IR access fill it in afterward.
    pub fn identity(&self) -> Identity {
        Identity {
            source_hash: self.source_hash.to_string(),
            vericl_version: crate::VERSION.to_string(),
            ir_hash: None,
        }
    }

    pub fn record(&self) -> ContractRecord {
        ContractRecord {
            assumes: self.assumes.iter().map(|s| s.to_string()).collect(),
            compare: self.compare.describe(),
            wrapping: self.wrapping,
            instantiate: self.instantiate.iter().map(|s| s.to_string()).collect(),
            uses: self.uses.iter().map(|s| s.to_string()).collect(),
        }
    }
}

/// Fold a kernel's or helper's own (compile-time) source hash together with
/// the already-computed identity hashes of every helper it directly
/// `uses(...)`, producing the hash actually recorded as identity.
///
/// This is the runtime half of kernel-composition identity (see
/// `crates/vericl-macros`' `#[vericl::helper]`/`uses(...)` design): a
/// kernel's `SOURCE_HASH` constant only ever covers its own source tokens
/// (computable at macro-expansion time), so it cannot by itself reflect a
/// change to a helper's body — that only exists as a separate, sibling
/// `SOURCE_HASH` constant vericl has no way to fold in at compile time
/// (macro invocations cannot see each other's output). Folding the used
/// helpers' hashes in here, at ordinary Rust runtime, closes that gap:
/// `<kernel>_vericl::identity()` calls this with `deps` built from each
/// `uses(...)`-listed helper's own `identity_hash()` (itself computed the
/// same way, recursively — see that function's generated doc), so a change
/// two levels deep in the helper-call graph still changes the top-level
/// kernel's recorded `source_hash`. An empty `deps` (the overwhelmingly
/// common case: a kernel/helper with no `uses(...)` clause) is a pure
/// pass-through, so this is a no-op for every kernel that doesn't compose —
/// existing evidence for such kernels is unaffected.
///
/// Recognizing more dependencies only ever changes the combined hash, never
/// silently drops a real change — the reverse (a dependency change that
/// fails to move the combined hash) would be the unsound direction, and
/// isn't possible here since every `deps` entry is mixed into the digest.
pub fn combine_source_hash(local: &str, deps: &[String]) -> String {
    if deps.is_empty() {
        return local.to_string();
    }
    let mut hasher = Sha256::new();
    hasher.update(local.as_bytes());
    for d in deps {
        hasher.update(b"||uses:");
        hasher.update(d.as_bytes());
    }
    format!("sha256:{:x}", hasher.finalize())
}

/// The deepest helper-composition chain `combine_source_hash`'s generated
/// callers (`identity()`/`identity_hash()`) will recurse through before
/// panicking (see [`check_helper_composition_depth`]) — a runtime backstop,
/// independent of and in addition to vericl-macros' best-effort
/// compile-time `uses(...)` cycle check (which cannot see across separate
/// macro invocations with full reliability; see that check's doc). 32 is
/// far beyond any plausible legitimate helper-call depth (v0's own examples
/// nest at most two deep) and cheap to check on every call.
pub const MAX_HELPER_COMPOSITION_DEPTH: u32 = 32;

/// Panics with an actionable message identifying `name` if `depth` has
/// reached [`MAX_HELPER_COMPOSITION_DEPTH`]. Called by every macro-generated
/// `identity()`/`identity_hash()` before it recurses into its own
/// `uses(...)`-listed dependencies. Without this, a recursive or
/// mutually-recursive `uses(...)` declaration that slipped past
/// vericl-macros' compile-time cycle check would make this combine hang
/// forever chasing its own tail instead of failing loudly and namely — a
/// silent hang is strictly worse than a clear panic naming the offending
/// item.
pub fn check_helper_composition_depth(name: &str, depth: u32) {
    assert!(
        depth < MAX_HELPER_COMPOSITION_DEPTH,
        "vericl: helper composition depth exceeded {MAX_HELPER_COMPOSITION_DEPTH} while \
         combining source-hash identity through `{name}` — this almost always means a \
         recursive or mutually-recursive uses(...) declaration slipped past vericl-macros' \
         compile-time cycle check; fix the uses(...) clauses so the helper-call graph is \
         acyclic"
    );
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn combine_source_hash_is_pass_through_with_no_deps() {
        assert_eq!(combine_source_hash("local-hash", &[]), "local-hash");
    }

    #[test]
    fn combine_source_hash_is_deterministic_and_dep_sensitive() {
        let a = combine_source_hash("local", &["dep-a".to_string()]);
        let a_again = combine_source_hash("local", &["dep-a".to_string()]);
        let b = combine_source_hash("local", &["dep-b".to_string()]);
        let two_deps = combine_source_hash("local", &["dep-a".to_string(), "dep-b".to_string()]);
        assert_eq!(a, a_again, "same inputs must hash identically");
        assert_ne!(a, "local", "folding in a dep must change the hash");
        assert_ne!(a, b, "a different dep hash must change the combined hash");
        assert_ne!(a, two_deps, "an extra dep must change the combined hash");
    }

    /// Direct test of the runtime depth guard's own threshold behavior —
    /// independent of whether a real compiling cycle can be constructed to
    /// exercise it end to end (see `crates/vericl-macros`'
    /// `register_and_check_cycle` doc: every cycle constructed by hand
    /// during this milestone's verification was in fact caught at compile
    /// time, so this guard is believed unreachable via vericl-macros'
    /// generated code in practice — this test pins the backstop itself
    /// works correctly regardless).
    #[test]
    fn helper_composition_depth_guard_trips_at_the_threshold() {
        for d in 0..MAX_HELPER_COMPOSITION_DEPTH {
            check_helper_composition_depth("ok", d); // must not panic
        }
        let trapped = std::panic::catch_unwind(|| {
            check_helper_composition_depth("cyclic_helper", MAX_HELPER_COMPOSITION_DEPTH);
        });
        assert!(trapped.is_err(), "depth == MAX must panic");
        let msg = *trapped.unwrap_err().downcast::<String>().expect("panic payload is a String");
        assert!(msg.contains("cyclic_helper"), "panic message should name the offending item: {msg}");
    }
}
